shape: sequence_diagram

c: Ninox Pro User {
  shape: person
}

pc: Ninox CLI: {
  icon: https://icons.terrastruct.com/tech%2Flaptop.svg
  shape: image
}

t: Ninox API: {
  icon: https://icons.terrastruct.com/essentials%2F112-server.svg
  shape: image
}

c -> pc: Download {
  shape: arrow
  style: solid
  label: Download ninox database 4321
}

pc -> t: GET https://templates.ninox.com/email {
  shape: arrow
  style: solid
  label: Get Database Information including Schema
}

t -> pc: Return the database info {
  style.stroke-dash: 5
}

pc -> pc: Parse Database Schema as per defined Types {
  style.stroke-dash: 5
}

pc -> pc: {
  style.stroke-dash: 5
  label: |md Write to files in local filesystem |
}

# pc -> o: {
#   shape: arrow
#   style: solid
#   label: Save to files in local filesystem
# }

pc -> c: {
  style.stroke-dash: 5
  label: Database 4321 Downloaded successfully!
}
