shape: sequence_diagram

# Participants
c: Ninox Pro User {
  shape: person
}

pc: Ninox CLI: {
  icon: https://icons.terrastruct.com/tech%2Flaptop.svg
  shape: image
}

t: Ninox API: {
  icon: https://icons.terrastruct.com/essentials%2F112-server.svg
  shape: image
}

fs: FSUtil {
  icon: https://icons.terrastruct.com/essentials%2F257-file.svg
  shape: image
}

# Diagram actions
c -> pc: Upload {
  shape: arrow
  style: solid
  label: Upload ninox database 4321
}

pc -> fs: Read Database Configs from Files {
  shape: arrow
  style: solid
  label: ReadDefinedDatabaseConfigsFromFiles()
}

fs -> pc: Return Parsed Configs {
  style.stroke-dash: 5
  label: Yaml database configs
}

pc -> pc: {
  style.stroke-dash: 5
  label: Parse Database Configs and Schema
}

pc -> t: POST https://api.ninox.com/databases/upload {
  shape: arrow
  style: solid
  label: Upload Database and Schema
}

t -> pc: Return Success Status {
  style.stroke-dash: 5
  label: Upload successful
}

pc -> c: {
  style.stroke-dash: 5
  label: Database 4321 Uploaded Successfully!
}
