name: Lint & Unit, Integration tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/develop' ||  github.ref == 'refs/heads/main') && github.run_number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: true
  NODE_ENV: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Cache node modules
        uses: actions/cache@v3
        continue-on-error: true
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: npm install
        run: |
          npm ci
      - name: npm linting
        run: |
          npm run lint

  unit_test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Cache node modules
        uses: actions/cache@v3
        continue-on-error: true
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: npm install
        run: |
          npm ci
      - name: Unit test
        run: |
          npm run test:unit

  integration_test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: npm install
        run: |
          npm ci
      - name: Integration test
        run: |
          npm run test:integration
